version: "3.7"
services:
  dev:
    container_name: bot-gpt
    image: bot-gpt:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - 3110:80
    entrypoint: scripts/entrypoint.sh
    volumes:
      - .:/code
    tty: true
    stdin_open: true